gawk -f add_vt.awk mori_64div.gex > vt/mori_64div.gex
gawk -f add_vt.awk mori_8-1seldec.gex > vt/mori_8-1seldec.gex
gawk -f add_vt.awk mori_8-1selor.gex > vt/mori_8-1selor.gex
gawk -f add_vt.awk mori_and2_v2.gex > vt/mori_and2_v2.gex
gawk -f add_vt.awk mori_bufx8_m.gex > vt/mori_bufx8_m.gex
gawk -f add_vt.awk mori_dff_v2.gex > vt/mori_dff_v2.gex
gawk -f add_vt.awk mori_er2_sw.gex > vt/mori_er2_sw.gex
gawk -f add_vt.awk mori_er4_sw.gex > vt/mori_er4_sw.gex
gawk -f add_vt.awk mori_er6_sw.gex > vt/mori_er6_sw.gex
gawk -f add_vt.awk mori_erunit.gex > vt/mori_erunit.gex
gawk -f add_vt.awk mori_erunit_sw.gex > vt/mori_erunit_sw.gex
gawk -f add_vt.awk mori_inv1_v2.gex > vt/mori_inv1_v2.gex
gawk -f add_vt.awk mori_inv1_v2_psw.gex > vt/mori_inv1_v2_psw.gex
gawk -f add_vt.awk mori_inv1_v2_special.gex > vt/mori_inv1_v2_special.gex
gawk -f add_vt.awk mori_inv1L2W12p22.gex > vt/mori_inv1L2W12p22.gex
gawk -f add_vt.awk mori_inv1L2W12p22_psw.gex > vt/mori_inv1L2W12p22_psw.gex
gawk -f add_vt.awk mori_inv1L2W14p22.gex > vt/mori_inv1L2W14p22.gex
gawk -f add_vt.awk mori_inv1L2W14p22_psw.gex > vt/mori_inv1L2W14p22_psw.gex
gawk -f add_vt.awk mori_inv1L3W50p75.gex > vt/mori_inv1L3W50p75.gex
gawk -f add_vt.awk mori_inv1L3W50p75_psw.gex > vt/mori_inv1L3W50p75_psw.gex
gawk -f add_vt.awk mori_inv1L4.gex > vt/mori_inv1L4.gex
gawk -f add_vt.awk mori_inv1L4_psw.gex > vt/mori_inv1L4_psw.gex
gawk -f add_vt.awk mori_m1m2_via.gex > vt/mori_m1m2_via.gex
gawk -f add_vt.awk mori_nand2_v2.gex > vt/mori_nand2_v2.gex
gawk -f add_vt.awk mori_nand3_v2.gex > vt/mori_nand3_v2.gex
gawk -f add_vt.awk mori_nand4_v2.gex > vt/mori_nand4_v2.gex
gawk -f add_vt.awk mori_nor2_v2.gex > vt/mori_nor2_v2.gex
gawk -f add_vt.awk mori_p50x3_m.gex > vt/mori_p50x3_m.gex
gawk -f add_vt.awk mori_poly_via.gex > vt/mori_poly_via.gex
gawk -f add_vt.awk mori_ring7.gex > vt/mori_ring7.gex
gawk -f add_vt.awk mori_ring7_nand.gex > vt/mori_ring7_nand.gex
gawk -f add_vt.awk mori_ring7_nor.gex > vt/mori_ring7_nor.gex
gawk -f add_vt.awk mori_ring7L2W12p22.gex > vt/mori_ring7L2W12p22.gex
gawk -f add_vt.awk mori_ring7L2W14p22.gex > vt/mori_ring7L2W14p22.gex
gawk -f add_vt.awk mori_ring7L3W50p75.gex > vt/mori_ring7L3W50p75.gex
gawk -f add_vt.awk mori_ring7L4.gex > vt/mori_ring7L4.gex
gawk -f add_vt.awk mori_rings_top.gex > vt/mori_rings_top.gex
gawk -f add_vt.awk mori_rings_top_no.gex > vt/mori_rings_top_no.gex
gawk -f add_vt.awk mori_rings_top_no_arg.gex > vt/mori_rings_top_no_arg.gex
