gawk -f gex_wire2box_rename.awk 64div.gex > box/mori_64div.gex
gawk -f gex_wire2box_rename.awk 8-1seldec.gex > box/mori_8-1seldec.gex
gawk -f gex_wire2box_rename.awk 8-1selor.gex > box/mori_8-1selor.gex
gawk -f gex_wire2box_rename.awk and2_v2.gex > box/mori_and2_v2.gex
gawk -f gex_wire2box_rename.awk bufx8_m.gex > box/mori_bufx8_m.gex
gawk -f gex_wire2box_rename.awk dff_v2.gex > box/mori_dff_v2.gex
gawk -f gex_wire2box_rename.awk er2_sw.gex > box/mori_er2_sw.gex
gawk -f gex_wire2box_rename.awk er4_sw.gex > box/mori_er4_sw.gex
gawk -f gex_wire2box_rename.awk er6_sw.gex > box/mori_er6_sw.gex
gawk -f gex_wire2box_rename.awk erunit.gex > box/mori_erunit.gex
gawk -f gex_wire2box_rename.awk erunit_sw.gex > box/mori_erunit_sw.gex
gawk -f gex_wire2box_rename.awk inv1_v2.gex > box/mori_inv1_v2.gex
gawk -f gex_wire2box_rename.awk inv1_v2_psw.gex > box/mori_inv1_v2_psw.gex
gawk -f gex_wire2box_rename.awk inv1_v2_special.gex > box/mori_inv1_v2_special.gex
gawk -f gex_wire2box_rename.awk inv1L2W14p22.gex > box/mori_inv1L2W14p22.gex
gawk -f gex_wire2box_rename.awk inv1L2W14p22_psw.gex > box/mori_inv1L2W14p22_psw.gex
gawk -f gex_wire2box_rename.awk inv1L4.gex > box/mori_inv1L4.gex
gawk -f gex_wire2box_rename.awk inv1L4_psw.gex > box/mori_inv1L4_psw.gex
gawk -f gex_wire2box_rename.awk m1m2_via.gex > box/mori_m1m2_via.gex
gawk -f gex_wire2box_rename.awk nand2_v2.gex > box/mori_nand2_v2.gex
gawk -f gex_wire2box_rename.awk nand3_v2.gex > box/mori_nand3_v2.gex
gawk -f gex_wire2box_rename.awk nand4_v2.gex > box/mori_nand4_v2.gex
gawk -f gex_wire2box_rename.awk nor2_v2.gex > box/mori_nor2_v2.gex
gawk -f gex_wire2box_rename.awk p50x3_m.gex > box/mori_p50x3_m.gex
gawk -f gex_wire2box_rename.awk poly_via.gex > box/mori_poly_via.gex
gawk -f gex_wire2box_rename.awk ring7.gex > box/mori_ring7.gex
gawk -f gex_wire2box_rename.awk ring7_nand.gex > box/mori_ring7_nand.gex
gawk -f gex_wire2box_rename.awk ring7_nor.gex > box/mori_ring7_nor.gex
gawk -f gex_wire2box_rename.awk ring7L2W14p22.gex > box/mori_ring7L2W14p22.gex
gawk -f gex_wire2box_rename.awk ring7L4.gex > box/mori_ring7L4.gex
gawk -f gex_wire2box_rename.awk rings_top2.gex > box/mori_rings_top2.gex
